In [96]:
import numpy as np

In [97]:
def swapRows(matrix, i, j):
    currentMatrix = matrix.copy()
    currentMatrix[[i, j]] = currentMatrix[[j, i]]
    return currentMatrix
def xorRowsInMatrix(matrix, firstRowIndex, secondRowIndex):
    currentMatrix = matrix.copy()
    currentMatrix[secondRowIndex] = np.logical_xor(currentMatrix[firstRowIndex], currentMatrix[secondRowIndex])
    return currentMatrix


1.1. Реализовать функцию REF(), приводящую матрицу к
ступенчатому виду.

In [98]:
def ref(inputMatrix):
    matrix = inputMatrix.copy()
    rows = matrix.shape[0]
    columns = matrix.shape[1]

    # Find and moving lead row
    indexForNextPositionOfLeadRow = 0
    indexColumnOfLeadingElement = -1
    while (True):
        isMoveLeadRow = False
        for i in range(indexColumnOfLeadingElement + 1, columns):
            for j in range(indexForNextPositionOfLeadRow, rows):
                if matrix[j][i]:
                    matrix = swapRows(matrix, indexForNextPositionOfLeadRow, j)
                    indexForNextPositionOfLeadRow += 1
                    indexColumnOfLeadingElement = i
                    isMoveLeadRow = True
                    break
            if (isMoveLeadRow):
                break
        if not isMoveLeadRow:
            return matrix[0: indexForNextPositionOfLeadRow]

        # Making xor with rows
        for j in range(indexForNextPositionOfLeadRow, rows):
            if matrix[j][indexColumnOfLeadingElement]:
                matrix = xorRowsInMatrix(matrix, indexForNextPositionOfLeadRow - 1, j)


In [99]:
matrix1 = np.array([[True, False, True, True, False, False, False, True, False, False, True],
                        [False, False, False, True, True, True, False, True, False, True, False],
                        [False, False, False, False, True, False, False, True, False, False, True],
                        [True, False, True, False, True, True, True, False, False, False, False],
                        [False, False, False, False, True, False, False, True, True, True, False],
                        [True, False, True, True, True, False, False, False, False, False, False]]
                        )
print(ref(matrix1))

[[ True False  True  True False False False  True False False  True]
 [False False False  True  True  True False  True False  True False]
 [False False False False  True False False  True False False  True]
 [False False False False False False  True False False  True  True]
 [False False False False False False False False  True  True  True]]


Реализовать функцию RREF(), приводящую матрицу к
приведённому ступенчатому виду.


In [100]:
def rref(inputMatrix):
    matrix = inputMatrix.copy()
    matrix = ref(matrix)
    rows = matrix.shape[0]
    columns = matrix.shape[1]

    for i in range(rows):
        for j in range(columns):
            if matrix[i][j]:
                for k in range(i):
                    if matrix[k][j]:
                        matrix = xorRowsInMatrix(matrix, i, k)
                break
    return matrix


In [101]:
print(rref(matrix1))

[[ True False  True False False  True False  True False  True False]
 [False False False  True False  True False False False  True  True]
 [False False False False  True False False  True False False  True]
 [False False False False False False  True False False  True  True]
 [False False False False False False False False  True  True  True]]


In [102]:
def getLeadIndexes(refMatrix):
    matrix = refMatrix.copy()
    rows = matrix.shape[0]
    columns = matrix.shape[1]

    leadIndexes = []
    for i in range(rows):
        for j in range(columns):
            if matrix[i][j]:
                leadIndexes.append(j)
                break
    return leadIndexes



In [103]:
print(matrix1.shape[0])
print(matrix1.shape[1])

6
11


**1.3.3 Сформировать проверочную матрицу на основе порождающей.**
**Для этого выполнить следующие шаги.**


**Шаг 1. Сформировать матрицу G**

∗ в приведённом ступенчатом виде

на основе порождающей.
Тестовый пример (Шаг 1):

In [104]:
G = np.array([[1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
              [0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
              [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]])
G_star = rref(G)
print("G* = \n", G_star)

G* = 
 [[1 0 1 0 0 1 0 1 0 1 0]
 [0 0 0 1 0 1 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 1]]


Шаг 2. Зафиксировать ведущие столбцы lead матрицы G
∗

In [105]:
def getLeadIndexes(refMatrix):
    matrix = refMatrix.copy()
    rows = matrix.shape[0]
    columns = matrix.shape[1]

    leadIndexes = []
    for i in range(rows):
        for j in range(columns):
            if matrix[i][j]:
                leadIndexes.append(j)
                break
    return leadIndexes

In [106]:
lead = getLeadIndexes(G_star)
print('lead = ',lead)

lead =  [0, 3, 4, 6, 8]


Шаг 3. Сформировать сокращённую матрицу X, удалив ведущие
столбцы матрицы G
∗
.

In [107]:
def getAbbreviatedMatrix(matrix, lead):
    return np.delete(matrix, lead, axis=1)

In [108]:
X = getAbbreviatedMatrix(G_star, lead)
print('X = \n',X)

X = 
 [[0 1 1 1 1 0]
 [0 0 1 0 1 1]
 [0 0 0 1 0 1]
 [0 0 0 0 1 0]
 [0 0 0 0 1 1]]


Шаг 4. Сформировать матрицу H, поместив в строки,
соответствующие позициям ведущих столбцов строки из X, а в
остальные – строки единичной матрицы.

In [111]:
def step4(refMatrix, leadIndexes):
    matrix = refMatrix.copy()
    rows = matrix.shape[0]
    print(rows)
    columns = matrix.shape[1]
    eye = np.eye(columns)
    resultMatrix = np.zeros((columns + rows, columns))
    matrixRowIndex = 0
    eyeRowIndex = 0
    for i in range(resultMatrix.shape[0]):
        if i in leadIndexes:
            resultMatrix[i] = matrix[matrixRowIndex]
            matrixRowIndex += 1
        else:
            resultMatrix[i] = eye[eyeRowIndex]
            eyeRowIndex += 1
    return resultMatrix

In [125]:
H = step4(X, lead)
print(step4(X, lead))

5
5
[[0. 1. 1. 1. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


1.4. Сформировать все кодовые слова длины n двумя способами.

1.4.1 Сложить все слова из порождающего множества, оставить
неповторяющиеся.

In [134]:
u = [1, 0, 1, 1, 0]
print("u = ", u)
v = np.dot(u,G) % 2
print("v = u@G = ", v)
print("v@H = ", np.dot(v,H) % 2)

e1 = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
print("\n\ne1 =", e1)
print("v + e1 =",(v + e1) % 2)
print("(v + e1)@H =",np.dot(((v + e1) % 2),H) % 2)

u =  [1, 0, 1, 1, 0]
v = u@G =  [1 0 1 1 1 0 1 0 0 1 0]
v@H =  [0. 0. 0. 0. 0. 0.]


e1 = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
v + e1 = [1 0 0 1 1 0 1 0 0 1 0]
(v + e1)@H = [0. 1. 0. 0. 0. 0.]


In [146]:
# Шаг 1: Вычисляем минимальное расстояние (d)
# Создаем список для хранения всех возможных пар различных кодовых слов
distances = []
n = 11
k = 5

print(G)

# Перебираем все пары различных кодовых слов и вычисляем расстояния
for i in range(k):
    for j in range(i + 1, k):
        word1 = G[i]
        word2 = G[j]

        distance = np.sum(np.abs(word1 - word2))
        distances.append(distance)

# Минимальное расстояние (d) равно минимальному значению из списка distances
d = min(distances)

# Шаг 2: Определяем кратность обнаруживаемой ошибки (t)
t = (d - 1) // 2

# Вывод результатов
print("Кодовое расстояние (d):", d)
print("Кратность обнаруживаемой ошибки (t):", t)

[[1 0 1 1 0 0 0 1 0 0 1]
 [0 0 0 1 1 1 0 1 0 1 0]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 1]]
Кодовое расстояние (d): 3
Кратность обнаруживаемой ошибки (t): 1
