# **Лабораторная работа 4.**



# Часть 1


4.1 Написать функцию формирования порождающей и проверочной
матриц расширенного кода Голея (24,12,8).


In [1]:
import numpy as np

# Задайте матрицу B
B = np.array([[1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
              [1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
              [0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1],
              [1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1],
              [1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1],
              [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1],
              [0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1],
              [0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1],
              [0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1],
              [1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
              [0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1],
              [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]])

# Создаем единичную матрицу 12x12
I = np.eye(12)

# Строим порождающую матрицу G
G = np.hstack((I, B))

# Строим проверочную матрицу H
H = np.vstack((I, B))

print("Порождающая матрица G:")
print(G)

print("Проверочная матрица H:")
print(H)


Порождающая матрица G:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]
Проверочная матрица H:
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 

4.2. Провести исследование расширенного кода Голея для одно-, двух-,
трёх- и четырёхкратных ошибок.

In [87]:
def encode(u, G):
    return np.dot(u, G) % 2
    
# 𝑤 = [0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0]
def decode(w, H):
    def wt(x):
        return np.sum(x % 2)
    # s - синдром
    s = np.dot(w, H) % 2
    if wt(s) <= 3:
        u = s.copy()
        print(u)
        u = np.hstack((u, [0,0,0,0,0,0,0,0,0,0,0,0]))
        print("Попали во 2 условие")
        return (u + w) % 2
    for i in range(B.shape[0]):
        b = B[i]
        if wt((s + b) % 2) <= 2:
            u = np.hstack(((s + b) % 2, I[i]))
            print("Попали в 3 условие", i)
            return (u + w) % 2
    second_syndrome = np.dot(s, B) % 2
    if wt(second_syndrome) <= 3:
        u = np.hstack(([0], second_syndrome))
        print("Попали в 5 условие")
        return u
    for i in range(B.shape[0]):
        b = B[i]
        if wt((second_syndrome + b) % 2) <= 2:
            u = np.hstack((I[i], (second_syndrome + b) % 2))
            print("Попали в 6 условие")
            return (u + w) % 2
    print("Ошибка не определена")
    raise Exception("Ошибка не определена")
    
# print("decode", decode(w, H))

u = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

# Исследование для однократной ошибки
code_word = encode(u, G)
print("code_word ", code_word)
error= [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  # Индекс бита, в который вносим ошибку
w = (code_word + error) % 2 # w - принятое слово с ошибками
corrected = decode(w, H)
print("w ", w)
print("w.shape ", w.shape)
print("corrected ", corrected)
print("corrected.shape ", corrected.shape)


code_word  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Попали во 2 условие
w  [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
w.shape  (24,)
corrected  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
corrected.shape  (24,)


In [88]:
error= [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  # Индекс бита, в который вносим ошибку
w = (code_word + error) % 2 # w - принятое слово с ошибками
corrected = decode(w, H)
print("w ", w)
print("w.shape ", w.shape)
print("corrected ", corrected)
print("corrected.shape ", corrected.shape)


[1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Попали во 2 условие
w  [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
w.shape  (24,)
corrected  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
corrected.shape  (24,)


In [89]:
error= [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  # Индекс бита, в который вносим ошибку
w = (code_word + error) % 2 # w - принятое слово с ошибками
corrected = decode(w, H)
print("w ", w)
print("w.shape ", w.shape)
print("corrected ", corrected)
print("corrected.shape ", corrected.shape)


[1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Попали во 2 условие
w  [0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
w.shape  (24,)
corrected  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
corrected.shape  (24,)


In [90]:
error= [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]  # Индекс бита, в который вносим ошибку
w = (code_word + error) % 2 # w - принятое слово с ошибками
corrected = decode(w, H)
print("w ", w)
print("w.shape ", w.shape)
print("corrected ", corrected)
print("corrected.shape ", corrected.shape)


Ошибка не определена


Exception: Ошибка не определена

# Часть 2


4.3 Написать функцию формирования порождающей и проверочных
матриц кода Рида-Маллера RM(r, m) на основе параметров r и m.

In [91]:
def generate_RideMaller_code(r, m):
    if 0 <= r <= m:
        if r == 0:
            G = np.array([1 for _ in range(2 ** m)], dtype=int)
        elif r == m:
            arr = np.array([0 for _ in range(2 ** m - 1)], dtype=int)
            last_str = np.append(arr, 1)
            G = np.vstack([
                generate_RideMaller_code(m - 1, m),
                last_str
            ])
        else:
            first = np.hstack([
                generate_RideMaller_code(r, m - 1),
                generate_RideMaller_code(r, m - 1),
            ])
            last = np.hstack([
                np.array([0 for _ in range(2 ** m - 2 ** (m - 1))], dtype=int),
                generate_RideMaller_code(r - 1, m - 1)
            ])
            G = np.vstack([
                first,
                last
            ])
        return G


4.4. Провести исследование кода Рида-Маллера RM(1,3) для одно- и
двукратных ошибок.

In [92]:
def createH(i, m):
    h = np.array([
        [1, 1],
        [1, -1]
    ], dtype=int)
    I_left = np.eye(2 ** (m - i), dtype=int)
    I_rigth = np.eye(2 ** (i - 1), dtype=int)
    H0 = np.kron(I_left,h)
    H = np.kron(H0, I_rigth)
    return H


def change(x):
    if x == 0:
        return -1
    else:
        return x


def kill_errors_in_RideMallerCode(m, G, count_errors):
    print("Внесение", count_errors, "ошибок в слово")
    word = np.random.randint(0, 2, len(G))
    print('word = ', word)
    code_word = np.dot(word, G) % 2
    print('code_word = ', code_word)
    error_position = np.random.choice(len(G[0] - 1), count_errors, replace=False)
    print('error_position =', error_position)
    code_word_with_error = np.copy(code_word)
    for i in error_position:
        code_word_with_error[i] = (code_word_with_error[i] + 1) % 2
    print("code_word_with_error = ", code_word_with_error)
    code_word_with_error = np.array(list(map(lambda x: change(x), code_word_with_error)), dtype=int)
    prev_syndrome = np.copy(code_word_with_error)
    maximum = -1
    pos_maximum = 0
    sign = True
    for i in range(0, m):
        H = createH(i + 1, m)
        print('H(' + str(i + 1) + ',' + str(m) + ') =\n', H)
        if i == 0:
            syndrome = np.dot(prev_syndrome, H)
        else:
            syndrome = np.dot(prev_syndrome, H)
        print("w(" + str(i + 1) + ")= ", syndrome)
        prev_syndrome = syndrome
        for i in range(len(syndrome)):
            if maximum < abs(syndrome[i]):
                maximum = abs(syndrome[i])
                pos_maximum = i
                if syndrome[i] >= 0:
                    sign = True
                else:
                    sign = False


    print('maximum =', maximum)
    print('pos_maximum =', pos_maximum)
    v = bin(pos_maximum)[2::][::-1]
    if len(v) < m:
        v += '0' * (m - len(v))
    if sign:
        v = '1' + v
    else:
        v = '0' + v
    print('v = ', v)


def study_RidaMaller_code(r, m):
    print("код Рида-Маллера")
    G = generate_RideMaller_code(r, m)
    print('G(1,3) =\n', G)

    count_errors = 1
    kill_errors_in_RideMallerCode(m, G, count_errors)
    print('')
    count_errors = 2
    kill_errors_in_RideMallerCode(m, G, count_errors)
    print('')


r = 1
m = 3
study_RidaMaller_code(r, m)

код Рида-Маллера
G(1,3) =
 [[1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1]]
Внесение 1 ошибок в слово
word =  [0 0 1 0]
code_word =  [0 0 1 1 0 0 1 1]
error_position = [5]
code_word_with_error =  [0 0 1 1 0 1 1 1]
H(1,3) =
 [[ 1  1  0  0  0  0  0  0]
 [ 1 -1  0  0  0  0  0  0]
 [ 0  0  1  1  0  0  0  0]
 [ 0  0  1 -1  0  0  0  0]
 [ 0  0  0  0  1  1  0  0]
 [ 0  0  0  0  1 -1  0  0]
 [ 0  0  0  0  0  0  1  1]
 [ 0  0  0  0  0  0  1 -1]]
w(1)=  [-2  0  2  0  0 -2  2  0]
H(2,3) =
 [[ 1  0  1  0  0  0  0  0]
 [ 0  1  0  1  0  0  0  0]
 [ 1  0 -1  0  0  0  0  0]
 [ 0  1  0 -1  0  0  0  0]
 [ 0  0  0  0  1  0  1  0]
 [ 0  0  0  0  0  1  0  1]
 [ 0  0  0  0  1  0 -1  0]
 [ 0  0  0  0  0  1  0 -1]]
w(2)=  [ 0  0 -4  0  2 -2 -2 -2]
H(3,3) =
 [[ 1  0  0  0  1  0  0  0]
 [ 0  1  0  0  0  1  0  0]
 [ 0  0  1  0  0  0  1  0]
 [ 0  0  0  1  0  0  0  1]
 [ 1  0  0  0 -1  0  0  0]
 [ 0  1  0  0  0 -1  0  0]
 [ 0  0  1  0  0  0 -1  0]
 [ 0  0  0  1  0  0  0 -1]]
w(3)=  [ 2 

4.5. Провести исследование кода Рида-Маллера RM(1,4) для одно-, двух-,
трёх- и четырёхкратных ошибок.

In [93]:
def full_study_RidaMaller_code(r, m):
    print("код Рида-Маллера")
    G = generate_RideMaller_code(r, m)
    print('G(1,4) =\n', G)

    count_errors = 1
    kill_errors_in_RideMallerCode(m, G, count_errors)
    print('')
    count_errors = 2
    kill_errors_in_RideMallerCode(m, G, count_errors)
    print('')
    count_errors = 3
    kill_errors_in_RideMallerCode(m, G, count_errors)
    print('')
    count_errors = 4
    kill_errors_in_RideMallerCode(m, G, count_errors)
    print('')

r = 1
m = 4
full_study_RidaMaller_code(r, m)

код Рида-Маллера
G(1,4) =
 [[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]
 [0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1]]
Внесение 1 ошибок в слово
word =  [1 0 0 0 0]
code_word =  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
error_position = [2]
code_word_with_error =  [1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1]
H(1,4) =
 [[ 1  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 1 -1  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1 -1  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1 -1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1 -1  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1  1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  1 -1  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  1 -1  0  0  0  0]
 [ 