In [1]:
import numpy as np

In [2]:
def swapRows(matrix, i, j):
    currentMatrix = matrix.copy()
    currentMatrix[[i, j]] = currentMatrix[[j, i]]
    return currentMatrix
def xorRowsInMatrix(matrix, firstRowIndex, secondRowIndex):
    currentMatrix = matrix.copy()
    currentMatrix[secondRowIndex] = np.logical_xor(currentMatrix[firstRowIndex], currentMatrix[secondRowIndex])
    return currentMatrix

def getLeadIndexes(refMatrix):
    matrix = refMatrix.copy()
    rows = matrix.shape[0]
    columns = matrix.shape[1]

    leadIndexes = []
    for i in range(rows):
        for j in range(columns):
            if matrix[i][j]:
                leadIndexes.append(j)
                break
    return leadIndexes

def ref(inputMatrix):
    matrix = inputMatrix.copy()
    rows = matrix.shape[0]
    columns = matrix.shape[1]

    # Find and moving lead row
    indexForNextPositionOfLeadRow = 0
    indexColumnOfLeadingElement = -1
    while (True):
        isMoveLeadRow = False
        for i in range(indexColumnOfLeadingElement + 1, columns):
            for j in range(indexForNextPositionOfLeadRow, rows):
                if matrix[j][i]:
                    matrix = swapRows(matrix, indexForNextPositionOfLeadRow, j)
                    indexForNextPositionOfLeadRow += 1
                    indexColumnOfLeadingElement = i
                    isMoveLeadRow = True
                    break
            if (isMoveLeadRow):
                break
        if not isMoveLeadRow:
            return matrix[0: indexForNextPositionOfLeadRow]

        # Making xor with rows
        for j in range(indexForNextPositionOfLeadRow, rows):
            if matrix[j][indexColumnOfLeadingElement]:
                matrix = xorRowsInMatrix(matrix, indexForNextPositionOfLeadRow - 1, j)


def rref(inputMatrix):
    matrix = inputMatrix.copy()
    matrix = ref(matrix)
    rows = matrix.shape[0]
    columns = matrix.shape[1]

    for i in range(rows):
        for j in range(columns):
            if matrix[i][j]:
                for k in range(i):
                    if matrix[k][j]:
                        matrix = xorRowsInMatrix(matrix, i, k)
                break
    return matrix

2.1. Сформировать порождающую матрицу линейного кода (7, 4, 3).  
Подсказка 1: Матрица формируется в виде: 
𝐺 =[𝐼𝑘|𝑋]. 
Подсказка 2: 
Чтобы d было равно трём, необходимо, чтобы в каждой строке матрицы-
дополнения X  было не меньше двух единиц, при этом не было двух 
повторяющихся строк.

In [3]:
# Если 𝐶имеет длину 𝑛, расстояние 𝑑 и размерность 𝑘, будем 
# обозначать такой код как линейный код  𝑛,𝑘,𝑑 . Эти три 
# параметра в полной мере характеризуют линейный код

# В нашем случае n=7 k=4 d=3
# I_k - это единичная матрица k на k
# X - это матрица-дополнения размерности k на n-k

I_4 = np.eye(4)
X = np.array([[1, 1, 0],
              [1, 0, 1],
              [0, 1, 1],
              [1, 1, 1]])

# Так как она и так уже ступенчатая, то ref от нее брать не нужно
G = np.hstack((I_4, X))

print("G =\n", G)

G =
 [[1. 0. 0. 0. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]]


2.2 Сформировать проверочную матрицу на основе порождающей.  
Подсказка 3: Проверочная матрица будет иметь вид
![Alt text](image.png)

In [4]:
I_3 = np.eye(3)
# Ааналогично нет смысла тянуть код из первой лабы
H = np.vstack((X, I_3))

print('H= \n', H)

H= 
 [[1. 1. 0.]
 [1. 0. 1.]
 [0. 1. 1.]
 [1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2.3 Сформировать  таблицу  синдромов  для  всех  однократных 
ошибок.

In [5]:
# Создаем таблицу синдромов
syndrome_map = {}

# Перебираем все возможные однократные ошибки
for i in range(7):
    error = np.zeros(7)
    error[i] = 1
    
    # Вычисляем синдром для данной ошибки
    syndrome = np.dot(error, H) % 2
    
    # Добавляем синдром в таблицу
    syndrome_map[tuple(syndrome)] = tuple(error)

# Выводим таблицу синдромов
for error, syndrome in syndrome_map.items():
    print(f"Ошибка: {error}  Синдром: {syndrome}")

Ошибка: (1.0, 1.0, 0.0)  Синдром: (1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
Ошибка: (1.0, 0.0, 1.0)  Синдром: (0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0)
Ошибка: (0.0, 1.0, 1.0)  Синдром: (0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0)
Ошибка: (1.0, 1.0, 1.0)  Синдром: (0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0)
Ошибка: (1.0, 0.0, 0.0)  Синдром: (0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0)
Ошибка: (0.0, 1.0, 0.0)  Синдром: (0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
Ошибка: (0.0, 0.0, 1.0)  Синдром: (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0)


2.4. Сформировать кодовое слово длины n из слова длины k. Внести 
однократную ошибку в сформированное слово. Вычислить синдром, 
исправить ошибку с использованием таблицы синдромов. Убедиться 
в правильности полученного слова.

In [6]:

word = np.array([1, 0, 1, 1])

# Формируем кодовое слово длины n
code_word = np.dot(word, G) % 2

# Вносим однократную ошибку
error_index = 2  # Индекс бита, в который вносим ошибку
code_word_with_error = code_word.copy()
code_word_with_error[error_index] = (code_word_with_error[error_index] + 1) % 2

# Вычисляем синдром
syndrome = np.dot(code_word_with_error, H) % 2

# Исправляем ошибку, используя таблицу синдромов
corrected_code_word = None
if tuple(syndrome) in syndrome_map:
    corrected_code_word = code_word_with_error.copy()
    for i, bit in enumerate(syndrome_map[tuple(syndrome)]):
        corrected_code_word[i] = (corrected_code_word[i] + bit) % 2
else:
    print("Ошибка не может быть исправлена.")

# Убеждаемся в правильности полученного слова
if np.array_equal(code_word, corrected_code_word):
    print("Ошибку успешно исправлено.")
else:
    print("Ошибка не была исправлена.")

print("Исходное кодовое слово:", code_word)
print("Кодовое слово с ошибкой:", code_word_with_error)
print("Исправленное кодовое слово:", corrected_code_word)

Ошибку успешно исправлено.
Исходное кодовое слово: [1. 0. 1. 1. 0. 1. 0.]
Кодовое слово с ошибкой: [1. 0. 0. 1. 0. 1. 0.]
Исправленное кодовое слово: [1. 0. 1. 1. 0. 1. 0.]


2.5. Сформировать кодовое слово длины n из слова длины k. Внести 
двукратную ошибку в сформированное слово. Вычислить синдром, 
исправить  ошибку  с  использованием  таблицы  синдромов. 
Убедиться, что полученное слово отличается от отправленного. 

In [7]:
# Задаем кодовое слово длины k
word = np.array([0, 0, 0, 0])

# Формируем кодовое слово длины n
code_word = np.dot(word, G) % 2

# Вносим двукратную ошибку
error_index_1 = 2  # Индекс первого бита, в который вносим ошибку
error_index_2 = 4  # Индекс второго бита, в который вносим ошибку
code_word_with_error = code_word.copy()
code_word_with_error[error_index_1] = (code_word_with_error[error_index_1] + 1) % 2
code_word_with_error[error_index_2] = (code_word_with_error[error_index_2] + 1) % 2

# Вычисляем синдром
syndrome = np.dot(code_word_with_error, H) % 2

# Исправляем ошибку, используя таблицу синдромов
corrected_code_word = None
if tuple(syndrome) in syndrome_map:
    corrected_code_word = code_word_with_error.copy()
    for i, bit in enumerate(syndrome_map[tuple(syndrome)]):
        corrected_code_word[i] = (corrected_code_word[i] + bit) % 2
else:
    print("Ошибка не может быть исправлена.")

# Убеждаемся, что полученное слово отличается от отправленного
if np.array_equal(code_word, corrected_code_word):
    print("Ошибки успешно исправлены.")
else:
    print("Ошибка не была исправлена.")

print("Исходное кодовое слово:", code_word)
print("Кодовое слово с ошибками:", code_word_with_error)
print("Исправленное кодовое слово:", corrected_code_word)

Ошибка не была исправлена.
Исходное кодовое слово: [0. 0. 0. 0. 0. 0. 0.]
Кодовое слово с ошибками: [0. 0. 1. 0. 1. 0. 0.]
Исправленное кодовое слово: [0. 0. 1. 1. 1. 0. 0.]


2.6. Сформировать порождающую матрицу линейного кода (n, k, 5).  
Подсказка 4: 
Чтобы d  было равно пяти, необходимо, чтобы  в  матрице X  (без учёта 
единичной матрицы слева):
* было не меньше 4 единиц в каждой строке; 
* сумма любых двух строк содержала не менее 3 единиц; 
* сумма любых трёх строк содержала не менее 2 единиц; 
* сумма любых четырёх строк содержала не менее 1 единицы; 

In [8]:
def generate_G(n, k):
    # Создаем матрицу размером (n-k) x n, состоящую из нулей
    X = np.zeros((n-k, n), dtype=int)

    while True:
        all_conditions_is_valid = True

        print("sdd")
        # Заполняем матрицу X наугад
        for i in range(n - k):
            for j in range(n):
                print("sdd")
                X[i][j] = np.random.choice([0, 1], size=1)
        print("wwwwww")
        # Проверяем условие
        # а) было не меньше 4 единиц в каждой строке;
        for  i in range(n - k):
            if sum(X[i]) < 4:
                all_conditions_is_valid = False
        print("ddddd   ")
        # Условия б, в, г
        for i in range(n - k):
            for j in range(i + 1, n - k):
                print(((X[i] + X[j]) % 2))
                if sum((X[i] + X[j]) % 2) < 3:
                    all_conditions_is_valid = False
                for v in range(j + 1, n - k):
                    if sum((X[i] + X[j] + X[v]) % 2) < 2:
                        all_conditions_is_valid = False
                    for m in range(v + 1, n - k):
                        if sum((X[i] + X[j] + X[v] + X[m]) % 2) < 1:
                            all_conditions_is_valid = False
        if all_conditions_is_valid:
            return np.hstack((np.eye(n-k, dtype=int), X))

n = 11
k = 6

G = generate_G(n, k)
print('G = \n',G)


sdd
sdd


2.7 Сформировать проверочную матрицу на основе порождающей. 