In [90]:
import numpy as np

**Лабораторная работа №3**

3.1 Написать функцию формирования порождающей и проверочной
матриц кода Хэмминга (2^r − 1, 2^r − r − 1, 3) на основе параметра r,

а также таблицы синдромов для всех однократных ошибок.

In [91]:
r = 3
n = 2**r - 1  # Длина кодового слова
k = n - r  # Количество информационных символов

# Создание матрицы P с первой строкой из единиц
X = np.zeros((k, r), dtype=int)

# Затем создайте оставшиеся строки матрицы P в соответствии с кодом Хэмминга
for i in range(r):
    for j in range(k):
        if (j >> i) & 1:  # Проверяем, установлен ли i-й бит в j-м индексе
            X[j, i] = 1
X[0, :] = 1
# Создание единичной матрицы I_k
I_k = np.eye(k, dtype=int)

# Порождающая матрица G
G = np.hstack((I_k, X))

print('G = \n', G)
H = np.vstack((X, np.eye(n-k)))
print('H = \n',H)


G = 
 [[1 0 0 0 1 1 1]
 [0 1 0 0 1 0 0]
 [0 0 1 0 0 1 0]
 [0 0 0 1 1 1 0]]
H = 
 [[1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [92]:
# Создаем таблицу синдромов
syndrome_map = {}

# Перебираем все возможные однократные ошибки
for i in range(H.shape[0]):
    error = np.zeros(H.shape[0])
    error[i] = 1
    
    # Вычисляем синдром для данной ошибки
    syndrome = np.dot(error, H) % 2
    
    # Добавляем синдром в таблицу
    syndrome_map[tuple(syndrome)] = tuple(error)

# Выводим таблицу синдромов
for syndrome, error in syndrome_map.items():
    print(f"Синдром: {syndrome} Ошибка: {error}")

Синдром: (1.0, 1.0, 1.0) Ошибка: (1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
Синдром: (1.0, 0.0, 0.0) Ошибка: (0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0)
Синдром: (0.0, 1.0, 0.0) Ошибка: (0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
Синдром: (1.0, 1.0, 0.0) Ошибка: (0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0)
Синдром: (0.0, 0.0, 1.0) Ошибка: (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0)


3.2 Провести  исследование  кода  Хэмминга  для  одно-,  двух- и
трёхкратных ошибок для 𝒓=𝟐,𝟑,𝟒

In [93]:
word = np.zeros(G.shape[0])
word[0] = 1
# word = np.array([1, 0, 0, 1])


# Формируем кодовое слово длины n
code_word = np.dot(word, G) % 2

# Вносим однократную ошибку
error_index = 0  # Индекс бита, в который вносим ошибку
code_word_with_error = code_word.copy()
code_word_with_error[error_index] = (code_word_with_error[error_index] + 1) % 2

# Вычисляем синдром
syndrome = np.dot(code_word_with_error, H) % 2
print(syndrome)
# Исправляем ошибку, используя таблицу синдромов
corrected_code_word = None
if tuple(syndrome) in syndrome_map:
    corrected_code_word = code_word_with_error.copy()
    for i, bit in enumerate(syndrome_map[tuple(syndrome)]):
        corrected_code_word[i] = (corrected_code_word[i] + bit) % 2
else:
    print("Ошибка не может быть исправлена.")

# Убеждаемся в правильности полученного слова
if np.array_equal(code_word, corrected_code_word):
    print("Ошибку успешно исправлено.")
else:
    print("Ошибка не была исправлена.")

print("Исходное кодовое слово:", code_word)
print("Кодовое слово с ошибкой:", code_word_with_error)
print("Исправленное кодовое слово:", corrected_code_word)

[1. 1. 1.]
Ошибку успешно исправлено.
Исходное кодовое слово: [1. 0. 0. 0. 1. 1. 1.]
Кодовое слово с ошибкой: [0. 0. 0. 0. 1. 1. 1.]
Исправленное кодовое слово: [1. 0. 0. 0. 1. 1. 1.]


Проверка для двухкратных ошибок

In [94]:
# Формируем кодовое слово длины n
code_word = np.dot(word, G) % 2

# Вносим двухкратную ошибку
error_index_1 = 1  # Индекс первого бита, в который вносим ошибку
error_index_2 = 2  # Индекс второго бита, в который вносим ошибку
code_word_with_error = code_word.copy()
code_word_with_error[error_index_1] = (code_word_with_error[error_index_1] + 1) % 2
code_word_with_error[error_index_2] = (code_word_with_error[error_index_2] + 1) % 2

# Вычисляем синдром
syndrome = np.dot(code_word_with_error, H) % 2
print(syndrome)
# Исправляем ошибку, используя таблицу синдромов
corrected_code_word = None
if tuple(syndrome) in syndrome_map:
    corrected_code_word = code_word_with_error.copy()
    for i, bit in enumerate(syndrome_map[tuple(syndrome)]):
        corrected_code_word[i] = (corrected_code_word[i] + bit) % 2
else:
    print("Ошибка не может быть исправлена.")

# Убеждаемся в правильности полученного слова
if np.array_equal(code_word, corrected_code_word):
    print("Ошибку успешно исправлено.")
else:
    print("Ошибка не была исправлена.")

print("Исходное кодовое слово:", code_word)
print("Кодовое слово с ошибкой:", code_word_with_error)
print("Исправленное кодовое слово:", corrected_code_word)

[1. 1. 0.]
Ошибка не была исправлена.
Исходное кодовое слово: [1. 0. 0. 0. 1. 1. 1.]
Кодовое слово с ошибкой: [1. 1. 1. 0. 1. 1. 1.]
Исправленное кодовое слово: [1. 1. 1. 1. 1. 1. 1.]


Проверка для трёхкратных ошибок

In [95]:

# Формируем кодовое слово длины n
code_word = np.dot(word, G) % 2

# Вносим двухкратную ошибку
error_index_1 = 0  # Индекс первого бита, в который вносим ошибку
error_index_2 = 1  # Индекс второго бита, в который вносим ошибку
error_index_3 = 2 # Индекс третьего бита, в который вносим ошибку
code_word_with_error = code_word.copy()
code_word_with_error[error_index_1] = (code_word_with_error[error_index_1] + 1) % 2
code_word_with_error[error_index_2] = (code_word_with_error[error_index_2] + 1) % 2
code_word_with_error[error_index_3] = (code_word_with_error[error_index_2] + 1) % 2

# Вычисляем синдром
syndrome = np.dot(code_word_with_error, H) % 2
print(syndrome)
# Исправляем ошибку, используя таблицу синдромов
corrected_code_word = None
if tuple(syndrome) in syndrome_map:
    corrected_code_word = code_word_with_error.copy()
    for i, bit in enumerate(syndrome_map[tuple(syndrome)]):
        corrected_code_word[i] = (corrected_code_word[i] + bit) % 2
else:
    print("Ошибка не может быть исправлена.")

# Убеждаемся в правильности полученного слова
if np.array_equal(code_word, corrected_code_word):
    print("Ошибку успешно исправлено.")
else:
    print("Ошибка не была исправлена.")

print("Исходное кодовое слово:", code_word)
print("Кодовое слово с ошибкой:", code_word_with_error)
print("Исправленное кодовое слово:", corrected_code_word)

[0. 1. 1.]
Ошибка не может быть исправлена.
Ошибка не была исправлена.
Исходное кодовое слово: [1. 0. 0. 0. 1. 1. 1.]
Кодовое слово с ошибкой: [0. 1. 0. 0. 1. 1. 1.]
Исправленное кодовое слово: None


3.3 Написать функцию формирования порождающей и проверочной
матриц расширенного кода Хэмминга (𝟐𝒓,𝟐𝒓 −𝒓−𝟏,𝟑)  на основе
параметра 𝒓, а также таблицы синдромов для всех однократных
ошибок

In [96]:
zeros_row = np.zeros((1, H.shape[1]))

H_zeros = np.vstack((H, zeros_row))

ones_column = np.ones((H_zeros.shape[0], 1))

H_Star = np.hstack((H_zeros, ones_column))
print('H* = \n',H_Star)

sums = []

# Перебираем каждую строку в матрице
for row in G:
    # Вычисляем сумму элементов в строке и добавляем её в список сумм
    row_sum = sum(row)
    sums.append(row_sum)

print("sum = ", sums)

b = [1 if num % 2 != 0 else 0 for num in sums]

G_Star = np.column_stack((G, b))

print("G* = \n", G_Star)

H* = 
 [[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [1. 1. 0. 1.]
 [1. 0. 0. 1.]
 [0. 1. 0. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 1.]]
sum =  [4, 2, 2, 3]
G* = 
 [[1 0 0 0 1 1 1 0]
 [0 1 0 0 1 0 0 0]
 [0 0 1 0 0 1 0 0]
 [0 0 0 1 1 1 0 1]]


Таблица синдромов для расширенных матриц Хэмминга

In [97]:
# Создаем таблицу синдромов
extended_syndrome_map = {}

# Перебираем все возможные однократные ошибки
for i in range(H_Star.shape[0]):
    error = np.zeros(H_Star.shape[0])
    error[i] = 1
    
    # Вычисляем синдром для данной ошибки
    syndrome = np.dot(error, H_Star) % 2
    
    # Добавляем синдром в таблицу
    extended_syndrome_map[tuple(syndrome)] = tuple(error)

# Выводим таблицу синдромов
for syndrome, error in extended_syndrome_map.items():
    print(f"Синдром: {syndrome} Ошибка: {error}")

Синдром: (1.0, 1.0, 1.0, 1.0) Ошибка: (1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0)
Синдром: (1.0, 0.0, 0.0, 1.0) Ошибка: (0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0)
Синдром: (0.0, 1.0, 0.0, 1.0) Ошибка: (0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0)
Синдром: (1.0, 1.0, 0.0, 1.0) Ошибка: (0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0)
Синдром: (0.0, 0.0, 1.0, 1.0) Ошибка: (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
Синдром: (0.0, 0.0, 0.0, 1.0) Ошибка: (0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0)


Провести исследование расширенного кода Хэмминга для одно-,
двух-, трёх- и четырёхкратных ошибок для 𝒓=𝟐,𝟑,𝟒.

In [98]:
word = np.zeros(G_Star.shape[0])
word[0] = 1
# Формируем кодовое слово длины n
code_word = np.dot(word, G_Star) % 2

# Вносим однократную ошибку
error_index = 0  # Индекс бита, в который вносим ошибку
code_word_with_error = code_word.copy()
code_word_with_error[error_index] = (code_word_with_error[error_index] + 1) % 2

# Вычисляем синдром
syndrome = np.dot(code_word_with_error, H_Star) % 2
print(syndrome)
# Исправляем ошибку, используя таблицу синдромов
corrected_code_word = None
if tuple(syndrome) in extended_syndrome_map:
    corrected_code_word = code_word_with_error.copy()
    for i, bit in enumerate(extended_syndrome_map[tuple(syndrome)]):
        corrected_code_word[i] = (corrected_code_word[i] + bit) % 2
else:
    print("Ошибка не может быть исправлена.")

# Убеждаемся в правильности полученного слова
if np.array_equal(code_word, corrected_code_word):
    print("Ошибку успешно исправлено.")
else:
    print("Ошибка не была исправлена.")

print("Исходное кодовое слово:", code_word)
print("Кодовое слово с ошибкой:", code_word_with_error)
print("Исправленное кодовое слово:", corrected_code_word)

[1. 1. 1. 1.]
Ошибку успешно исправлено.
Исходное кодовое слово: [1. 0. 0. 0. 1. 1. 1. 0.]
Кодовое слово с ошибкой: [0. 0. 0. 0. 1. 1. 1. 0.]
Исправленное кодовое слово: [1. 0. 0. 0. 1. 1. 1. 0.]


Проверка для двухкратных ошибок

In [99]:
# Формируем кодовое слово длины n
code_word = np.dot(word, G_Star) % 2

# Вносим двухкратную ошибку
error_index_1 = 0  # Индекс первого бита, в который вносим ошибку
error_index_2 = 1  # Индекс второго бита, в который вносим ошибку
code_word_with_error = code_word.copy()
code_word_with_error[error_index_1] = (code_word_with_error[error_index_1] + 1) % 2
code_word_with_error[error_index_2] = (code_word_with_error[error_index_2] + 1) % 2

# Вычисляем синдром
syndrome = np.dot(code_word_with_error, H_Star) % 2
print(syndrome)
# Исправляем ошибку, используя таблицу синдромов
corrected_code_word = None
if tuple(syndrome) in extended_syndrome_map:
    corrected_code_word = code_word_with_error.copy()
    for i, bit in enumerate(extended_syndrome_map[tuple(syndrome)]):
        corrected_code_word[i] = (corrected_code_word[i] + bit) % 2
else:
    print("Ошибка не может быть исправлена.")

# Убеждаемся в правильности полученного слова
if np.array_equal(code_word, corrected_code_word):
    print("Ошибку успешно исправлено.")
else:
    print("Ошибка не была исправлена.")

print("Исходное кодовое слово:", code_word)
print("Кодовое слово с ошибкой:", code_word_with_error)
print("Исправленное кодовое слово:", corrected_code_word)

[0. 1. 1. 0.]
Ошибка не может быть исправлена.
Ошибка не была исправлена.
Исходное кодовое слово: [1. 0. 0. 0. 1. 1. 1. 0.]
Кодовое слово с ошибкой: [0. 1. 0. 0. 1. 1. 1. 0.]
Исправленное кодовое слово: None


Проверка для трёхкратных ошибок

In [100]:
# Формируем кодовое слово длины n
code_word = np.dot(word, G_Star) % 2

# Вносим двухкратную ошибку
error_index_1 = 0  # Индекс первого бита, в который вносим ошибку
error_index_2 = 1  # Индекс второго бита, в который вносим ошибку
error_index_3 = 2 # Индекс третьего бита, в который вносим ошибку
code_word_with_error = code_word.copy()
code_word_with_error[error_index_1] = (code_word_with_error[error_index_1] + 1) % 2
code_word_with_error[error_index_2] = (code_word_with_error[error_index_2] + 1) % 2
code_word_with_error[error_index_3] = (code_word_with_error[error_index_2] + 1) % 2

# Вычисляем синдром
syndrome = np.dot(code_word_with_error, H_Star) % 2
print(syndrome)
# Исправляем ошибку, используя таблицу синдромов
corrected_code_word = None
if tuple(syndrome) in extended_syndrome_map:
    corrected_code_word = code_word_with_error.copy()
    for i, bit in enumerate(extended_syndrome_map[tuple(syndrome)]):
        corrected_code_word[i] = (corrected_code_word[i] + bit) % 2
else:
    print("Ошибка не может быть исправлена.")

# Убеждаемся в правильности полученного слова
if np.array_equal(code_word, corrected_code_word):
    print("Ошибку успешно исправлено.")
else:
    print("Ошибка не была исправлена.")

print("Исходное кодовое слово:", code_word)
print("Кодовое слово с ошибкой:", code_word_with_error)
print("Исправленное кодовое слово:", corrected_code_word)

[0. 1. 1. 0.]
Ошибка не может быть исправлена.
Ошибка не была исправлена.
Исходное кодовое слово: [1. 0. 0. 0. 1. 1. 1. 0.]
Кодовое слово с ошибкой: [0. 1. 0. 0. 1. 1. 1. 0.]
Исправленное кодовое слово: None
